"""Shared fixture for the current Queue writer lifecycle."""

import json
from pathlib import Path
import subprocess
import sys

TESTS = Path(__file__).resolve().parents[1]
TOOLS = TESTS.parent
FIXTURE = TOOLS / "tests" / "fixtures" / "runtime_state" / "valid"
sys.path.insert(0, str(TOOLS / "tests"))
sys.path.insert(0, str(TOOLS))

import Tools.execution.audit.changed_scope_evidence_contract as changed_scope_evidence_contract
from Tools.execution.task_runtime import queue_runtime
import Tools.execution.task_runtime.runtime_validation as runtime_validation
import Tools.knowledge.metadata.compose_page_contract as compose_page_contract
import Tools.knowledge.metadata.compose_vocab as compose_vocab
import Tools.platform.common.kblib as kblib
import Tools.governance.profile.profile_admission as profile_admission
import Tools.governance.profile.profile_batch_judgment_contract as profile_batch_judgment_contract
import Tools.execution.task_runtime.runtime_paths as runtime_paths
from Tools.tests.support.initial_task_plan_fixture import (  # noqa: E402
    install_initial_task_plan_fixture,
)
from Tools.tests.support.coverage_delta_fixture import write_premerge_delta


class UpdateQueueFixture:
    """E2E-only actions required to generate Queue checkpoints."""

    def load(self, relative):
        return kblib.load_yaml_file(self.root / relative)

    def command(self, *args):
        return subprocess.run(
            [sys.executable, str(TOOLS / "update_queue.py"), str(self.root),
             *args], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            check=False,
        )

    def run_tool(self, name, *arguments):
        return subprocess.run(
            [sys.executable, str(TOOLS / name), str(self.root), *arguments],
            text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            check=False,
        )

    def install_plain_s_audit_fixture(self):
        """Install one legal bounded S-tier lifecycle fixture.

        Queue tests exercise transitions, rollback, and recovery rather than
        M-tier judgment.  Their common pages therefore use the selected
        Profile's actual page contract, and the compiled Profile artifacts are
        generated by their production compilers.  This keeps every scenario
        on the real AuditPlan path without adding fixture-only exceptions.
        """
        for name in ("A", "B"):
            (self.root / ("Topics/%s.md" % name)).write_text(
                "---\n"
                "type: concept\n"
                "domain: general\n"
                "scope: shared\n"
                "level: basic\n"
                "depth: atomic\n"
                "priority: P2\n"
                "---\n"
                "# %s\n\n"
                "## Synthetic Residual\n\n"
                "Accepted-root liveness marker for the registered fixture "
                "scan.\n" % name,
                encoding="utf-8",
            )

        coverage_path = self.root / queue_runtime.COVERAGE_PATH
        progress_path = self.root / queue_runtime.PROGRESS_PATH
        coverage = self.load(queue_runtime.COVERAGE_PATH)
        for page in coverage["pages"]:
            page["tier"] = "S"
            page["priority"] = "P2"
        coverage_path.write_text(
            kblib.canonical_yaml(coverage), encoding="utf-8")

        progress = self.load(queue_runtime.PROGRESS_PATH)
        progress["checkpoint"]["coverage_sha256"] = \
            kblib.sha256_file(coverage_path)
        progress_path.write_text(
            kblib.canonical_yaml(progress), encoding="utf-8")

        # This is an alternate *legal plan*, not a post-plan direct Coverage
        # edit. Rebuild the shared Task Plan transaction once so every later
        # lifecycle test starts from the same receipt-bound authority.
        install_initial_task_plan_fixture(self.root)

        admission, errors = profile_admission.admit_profile(self.root)
        self.assertEqual([], errors, errors)
        self.assertIsNotNone(admission)
        vocab_text, _vocab, errors = compose_vocab.compiled_artifact(
            self.root, admission)
        self.assertEqual([], errors, errors)
        page_contract_text, _contract, errors = \
            compose_page_contract.compiled_artifact(self.root, admission)
        self.assertEqual([], errors, errors)
        derived = self.root / runtime_paths.DERIVED_ROOT
        derived.mkdir(parents=True, exist_ok=True)
        (derived / "vocab.yaml").write_text(vocab_text, encoding="utf-8")
        (derived / "page_contract.yaml").write_text(
            page_contract_text, encoding="utf-8")
        self.assertEqual([], runtime_validation.validate_runtime(self.root)["errors"])

    def write_delta(self, batch_id, object_path, receipt_id, *,
                    open_gaps_added=None, open_gaps_closed=None,
                    generated_at="2026-08-04T02:00:00Z"):
        relative = ".cambium/deltas/%s.yaml" % batch_id
        return write_premerge_delta(
            self.root, relative, batch_id, object_path, [receipt_id],
            generated_at=generated_at,
            open_gaps_added=open_gaps_added or (),
            open_gaps_closed=open_gaps_closed or ())

    def prepare_premerge_audit_evidence(self, batch_id):
        """Create and discharge the real pre-merge AuditPlan closure."""
        prepared = self.run_tool(
            "prepare_audit_plan.py", "--batch", batch_id, "--apply")
        self.assertEqual(0, prepared.returncode, prepared.stdout)
        plan_result = json.loads(prepared.stdout)
        plan_path = plan_result["plan_path"]
        plan = self.load(plan_path)
        page_receipts = []
        produced_by_obligation = {}

        for obligation in plan["obligations"]:
            if (obligation.get("status") != "required" or
                    obligation.get("due_stage") != "pre-merge"):
                continue
            if obligation.get("evidence_kind") == \
                    profile_batch_judgment_contract.RECORD_KIND:
                # Profile judgments are deliberately produced by the actor
                # named in the Profile.  The mechanical helper leaves that
                # obligation to ``judge`` instead of impersonating the role.
                continue
            common = (
                "--batch", batch_id,
                "--plan", plan_path,
                "--obligation-id", obligation["obligation_id"],
            )
            if obligation["evidence_kind"] == "batch-page-review-record":
                produced = self.run_tool(
                    "record_batch_page_review.py", *common,
                    "--page", obligation["target"],
                    "--variant", "s-sampled-page",
                    "--reviewer-context-id", "fixture-review-context",
                    "--reviewer-role", "reviewer",
                    "--verdict", "passed",
                    "--statement",
                    "fixture page satisfies the frozen sampled-review "
                    "acceptance contract",
                    "--apply",
                )
                self.assertEqual(0, produced.returncode, produced.stdout)
                evidence = json.loads(produced.stdout)
                page_receipts.append(evidence["receipt_id"])
                produced_by_obligation[obligation["obligation_id"]] = {
                    "evidence_receipt": evidence["receipt_id"],
                    "audit_receipt": None,
                }
                continue

            if obligation["producer_check"] == "substantive_review":
                produced = self.run_tool(
                    "record_substantive_review.py", *common,
                    "--page", obligation["target"],
                    "--authoring-context-id", "fixture-author-context",
                    "--reviewer-context-id", "fixture-review-context",
                    "--reviewer-role", "reviewer",
                    "--round", "1", "--verdict", "passed",
                    "--statement",
                    "fixture independent substantive review confirms the "
                    "page satisfies the frozen acceptance contract",
                    "--apply",
                )
            elif obligation["producer_check"] == \
                    "changed_scope_rendering_escalation_record":
                produced = self.run_tool(
                    "record_rendering_verification.py", *common,
                    "--rendering-mode", "source-only", "--apply")
            elif (obligation.get("producer_capability") ==
                  changed_scope_evidence_contract.ADAPTER_CAPABILITY_ID or
                  obligation.get("producer_gate_id") is not None):
                produced = self.run_tool(
                    "record_changed_scope_evidence.py", *common, "--apply")
            else:
                self.fail(
                    "fixture has no producer dispatch for AuditPlan "
                    "obligation %s" % obligation["obligation_id"])
            self.assertEqual(0, produced.returncode, produced.stdout)
            evidence = json.loads(produced.stdout)
            if obligation["producer_check"] == "substantive_review":
                page_receipts.append(evidence["receipt_id"])
            audit_receipt_id = None
            if obligation["evidence_kind"] == "audit-receipt":
                completed = self.run_tool(
                    "complete_audit_receipt.py", *common,
                    "--evidence-receipt", evidence["receipt_id"],
                    "--apply",
                )
                self.assertEqual(0, completed.returncode, completed.stdout)
                audit_receipt_id = json.loads(completed.stdout)["receipt_id"]
            produced_by_obligation[obligation["obligation_id"]] = {
                "evidence_receipt": evidence["receipt_id"],
                "audit_receipt": audit_receipt_id,
            }

        self.assertEqual(1, len(page_receipts), plan)
        return {
            "plan": plan,
            "plan_path": plan_path,
            "page_receipt": page_receipts[0],
            "produced_by_obligation": produced_by_obligation,
        }

    def record_batch_review_wrapper(self, batch_id):
        reviewed = self.run_tool(
            "record_batch_review.py", "--batch", batch_id,
            "--actor-role", "integrator",
            "--statement",
            "fixture integrator confirms the complete frozen pre-merge "
            "AuditPlan evidence closure",
            "--apply", "--json",
        )
        self.assertEqual(0, reviewed.returncode, reviewed.stdout)
        receipts = json.loads(reviewed.stdout)
        self.assertEqual(1, len(receipts), receipts)
        return receipts[0]["receipt_id"]

    def prepare_merge_ready_closure(self, batch_id, object_path, **delta):
        audit = self.prepare_premerge_audit_evidence(batch_id)
        delta_path = self.write_delta(
            batch_id, object_path, audit["page_receipt"], **delta)
        batch_receipt = self.record_batch_review_wrapper(batch_id)
        return {
            **audit,
            "delta_path": delta_path,
            "batch_receipt": batch_receipt,
        }

    def expected(self):
        queue = self.load(queue_runtime.QUEUE_PATH)
        return str(queue["state_revision"]), kblib.sha256_file(
            self.root / queue_runtime.QUEUE_PATH)

    def queue_gate(self, *mode):
        relative = ".cambium/receipts/gates.jsonl"
        completed = subprocess.run(
            [sys.executable, str(TOOLS / "check_queue.py"), str(self.root),
             *mode, "--receipts", relative], text=True,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False,
        )
        self.assertEqual(0, completed.returncode, completed.stdout)
        records = [json.loads(line) for line in
                   (self.root / relative).read_text(encoding="utf-8").splitlines()]
        return records[-1]["receipt_id"]

    def open_b1(self):
        gate = self.queue_gate("--require-ready", "B1")
        revision, fingerprint = self.expected()
        completed = self.command(
            "--id", "B1", "--transition", "open",
            "--gate-receipt", gate,
            "--expected-state-revision", revision,
            "--expected-sha256", fingerprint,
            "--actor-role", "integrator", "--at", "2026-08-04T01:00:00Z",
            "--apply",
        )
        self.assertEqual(0, completed.returncode, completed.stdout)
        return completed

__all__ = [
    "UpdateQueueFixture",
]
