package profile

// GENERATED Tool encoding projection: do not edit this file.
// Encoding owner: Tools/governance/profile/profile-encoding.yaml
// Encoding SHA256: 96bd86b94a1c001b55050cf7725466323a3a25f427f7236830767a301269f5a2
// Semantic interface: kernel/K00 Standards Control/profile-interface.yaml
// Semantic interface SHA256: f4f4bf40e0aed8a8fe7ef9e527665a84709126ff7f54dc45118e93afe2ff2683
// Kernel slot/value domains remain unchanged by this document wrapper.
// Draft input does not supply defaults, confirmation, selection, or adoption.
// Directory identity spelling/equality remain with profile_layout_contract.
#OverrideValue: string | bool | number
#ProfileDraft: {
    schema_version?: 1
    profile_id?: #Text
    execution_default_overrides?: {[string]: #OverrideValue}
    "slots"?: #SlotFields
}
#Profile: #ProfileDraft & {
    schema_version: 1
    profile_id: #Text
    "slots": #ProfileSlots
}
