#!/usr/bin/env python3
"""Derived structure projection renderer — the registered generator for
Structure Registry roles declared `mode: derived`.

Rule owners:
- "kernel/K01 Scope and Architecture/05 Structural Unit Interface.md"
  (derived roles: generated by a deterministic tool, regenerated or
  invalidated when inputs change, never a canonical owner);
- "kernel/K01 Scope and Architecture/06 Support Layer Structural
  Interfaces.md" (support-layer coverage projections and derived indexes).

For every unit or support layer in the selected profile's Structure Registry
whose `coverage` role is `derived` and names this tool as `generator`, the
projection is computed from the Capability Matrix (rows whose canonical
paths sit under the unit root) plus Coverage Ledger dispositions. A role
with a rendering target (`path` + `heading`) owns exactly the block between
the `<!-- structure-projection:begin -->` / `<!-- structure-projection:end -->`
markers inside that section: `--apply` inserts or replaces only that block
(first position in the section on first insertion) and preserves every other
line, so curated reader prose in the same section is conserved. A role with
no rendering target renders to stdout only.

The block is a pure projection: it copies no Queue lifecycle, holds, batch
order, or receipts, and it never writes back into planning artifacts or page
classification.

Modes: default = report what would render; --check = exit 2 when any owned
block is stale or missing; --apply = write the owned blocks atomically.

Exit codes: 0 = current / applied, 1 = input error, 2 = --check stale.

Usage: python3 render_structure_projection.py <vault_root>
       [--profile PROFILE_DIR] [--check | --apply]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kblib
import profile_admission

TOOL = "render_structure_projection"
TOOL_VERSION = "1.1.0"

ACTIVE_STATE_PATH = "kernel/K00 Standards Control/03 Standards Governance.md"
STRUCTURE_SLOT = "Structure Registry"
COVERAGE_LEDGER_PATH = ".cambium/state/coverage_ledger.yaml"
BEGIN = "<!-- structure-projection:begin -->"
END = "<!-- structure-projection:end -->"


def read_text(path):
    with open(path, encoding="utf-8", errors="replace") as handle:
        return handle.read()


def registry_document(admission, errors):
    path, error = profile_admission.require_slot(admission, STRUCTURE_SLOT)
    if error:
        errors.append(error)
        return None
    try:
        return kblib.parse_yaml_subset(
            admission.slot_text(STRUCTURE_SLOT))
    except (OSError, UnicodeError, kblib.YamlSubsetError) as exc:
        errors.append("cannot parse the registry: %s" % exc)
        return None


def load_matrix(root, relative, errors):
    """Bind and parse one registry-declared Capability Matrix revision."""
    try:
        snapshot = kblib.repository_file_snapshot(
            root, relative, singly_linked=True)
        data = kblib.parse_yaml_subset(snapshot.read_text())
    except (OSError, UnicodeError, ValueError,
            kblib.YamlSubsetError) as exc:
        errors.append("cannot bind derived-role inputs_owner %r: %s" %
                      (relative, exc))
        return [], None
    if not isinstance(data, dict) or not isinstance(
            data.get("capabilities"), list):
        errors.append("derived-role inputs_owner %r has no capabilities list" %
                      relative)
        return [], snapshot
    return data["capabilities"], snapshot


def load_dispositions(root, errors):
    path = os.path.join(root, COVERAGE_LEDGER_PATH)
    if not os.path.isfile(path):
        return {}, None
    try:
        snapshot = kblib.repository_file_snapshot(
            root, COVERAGE_LEDGER_PATH, singly_linked=True)
        data = kblib.parse_yaml_subset(snapshot.read_text())
    except (OSError, UnicodeError, ValueError,
            kblib.YamlSubsetError) as exc:
        errors.append("cannot bind Coverage Ledger projection input: %s" % exc)
        return {}, None
    out = {}
    for page in (data or {}).get("pages") or []:
        if isinstance(page, dict) and page.get("path"):
            out[str(page["path"])] = str(
                page.get("coverage_disposition") or "")
    return out, snapshot


def input_currency_errors(root, snapshots):
    errors = []
    for snapshot in snapshots:
        if snapshot is None:
            continue
        try:
            current = kblib.repository_file_snapshot(
                root, snapshot.repository_path, singly_linked=True)
        except (OSError, ValueError) as exc:
            errors.append("cannot re-bind projection input %s: %s" %
                          (snapshot.repository_path, exc))
            continue
        if current.sha256 != snapshot.sha256:
            errors.append("projection input %s changed during rendering" %
                          snapshot.repository_path)
    return errors


def under_root(path, unit_root):
    return path == unit_root or path.startswith(unit_root + "/")


def render_block(unit_id, unit_root, matrix, dispositions):
    """Deterministic projection lines for one unit or layer."""
    rows = []
    for cap in matrix:
        if not isinstance(cap, dict):
            continue
        owners = [str(p) for p in cap.get("canonical_markdown_paths") or []]
        mine = [p for p in owners if under_root(p, unit_root)]
        if not mine:
            continue
        gaps = ", ".join(str(g) for g in cap.get("gap_ids") or []) or "none"
        rows.append("| `%s` | %s | %s | %s | %s | %s |" % (
            cap.get("capability_id"), cap.get("capability"),
            cap.get("current_level"), cap.get("target_level"),
            "; ".join("[[%s\\|%s]]" % (p[:-3] if p.endswith(".md") else p,
                                       os.path.basename(p)[:-3]
                                       if p.endswith(".md")
                                       else os.path.basename(p))
                      for p in mine),
            gaps))
    page_total = sum(1 for p in dispositions if under_root(p, unit_root))
    required = sum(1 for p, d in dispositions.items()
                   if under_root(p, unit_root) and d == "required")
    lines = [BEGIN,
             "Derived projection for `%s` — generated by "
             "`Tools/render_structure_projection.py` from the Capability "
             "Matrix and Coverage Ledger; regenerate instead of editing. "
             "The canonical owners remain `Corpus Planning/` and "
             "`.cambium/state/coverage_ledger.yaml`." % unit_id]
    if rows:
        lines += ["",
                  "| Capability | Name | Current | Target | Canonical "
                  "owners here | Gaps |",
                  "|---|---|---|---|---|---|"] + rows
    else:
        lines += ["", "No Capability Matrix row names a canonical owner "
                      "under this root."]
    if page_total:
        lines += ["", "Coverage Ledger records %d page(s) under this root, "
                      "%d of them `required`." % (page_total, required)]
    lines.append(END)
    return lines


def replace_section_block(text, heading, block_lines):
    """Return (new_text, found_heading, changed)."""
    lines = text.splitlines()
    out = []
    i = 0
    found = False
    changed = False
    n = len(lines)
    while i < n:
        line = lines[i]
        out.append(line)
        i += 1
        stripped = line.strip()
        if not stripped.startswith("#"):
            continue
        level = len(stripped) - len(stripped.lstrip("#"))
        title = stripped.lstrip("#").strip()
        if title != heading.strip():
            continue
        found = True
        # collect the section body up to the next heading of <= level
        body = []
        while i < n:
            peek = lines[i].strip()
            if peek.startswith("#"):
                peek_level = len(peek) - len(peek.lstrip("#"))
                if peek_level <= level:
                    break
            body.append(lines[i])
            i += 1
        # replace or insert the marker block
        if BEGIN in [b.strip() for b in body]:
            new_body = []
            in_block = False
            replaced = False
            for b in body:
                if b.strip() == BEGIN:
                    in_block = True
                    if not replaced:
                        new_body.extend(block_lines)
                        replaced = True
                    continue
                if b.strip() == END:
                    in_block = False
                    continue
                if not in_block:
                    new_body.append(b)
        else:
            new_body = ["", *block_lines, *body]
        if new_body != body:
            changed = True
        out.extend(new_body)
    return "\n".join(out) + ("\n" if text.endswith("\n") else ""), \
        found, changed


def iter_derived_targets(registry):
    for kind_name in ("units", "support_layers"):
        for item in registry.get(kind_name) or []:
            if not isinstance(item, dict):
                continue
            if kind_name == "units":
                roles = item.get("roles")
                role = roles.get("coverage") \
                    if isinstance(roles, dict) else None
            else:
                role = item.get("coverage")
            if not isinstance(role, dict) or role.get("mode") != "derived":
                continue
            generator = str(role.get("generator") or "")
            if not generator.endswith("render_structure_projection.py"):
                continue
            yield (item.get("id") or item.get("layer_id"),
                   item.get("root"), role.get("inputs_owner"),
                   role.get("path"), role.get("heading"))


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Render derived Structure Registry coverage "
                    "projections (K01/05 derived roles).")
    parser.add_argument("vault_root")
    parser.add_argument("--profile")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    root = os.path.abspath(args.vault_root)

    errors = []
    admission, admission_errors = profile_admission.admit_profile(
        root, args.profile, active_state_path=ACTIVE_STATE_PATH)
    errors.extend(admission_errors)
    registry = registry_document(admission, errors) \
        if admission else None
    if registry is None:
        for error in errors:
            print("render_structure_projection: %s" % error)
        return 1

    targets = list(iter_derived_targets(registry))
    matrices = {}
    input_snapshots = []
    for _unit_id, _unit_root, inputs_owner, _path, _heading in targets:
        if inputs_owner in matrices:
            continue
        matrix, snapshot = load_matrix(root, inputs_owner, errors)
        matrices[inputs_owner] = matrix
        input_snapshots.append(snapshot)
    dispositions, coverage_snapshot = load_dispositions(root, errors)
    input_snapshots.append(coverage_snapshot)
    if errors:
        for error in errors:
            print("render_structure_projection: %s" % error)
        return 1
    stale = 0
    written = 0
    reported = 0
    pending = []
    for unit_id, unit_root, inputs_owner, path, heading in targets:
        block = render_block(
            unit_id, unit_root, matrices.get(inputs_owner, []), dispositions)
        if not path or not heading:
            reported += 1
            print("render_structure_projection: %s renders on demand "
                  "(no page target); %d projection line(s)"
                  % (unit_id, len(block)))
            continue
        target = os.path.join(root, path)
        if not os.path.isfile(target):
            print("render_structure_projection: %s target %r does not exist"
                  % (unit_id, path))
            stale += 1
            continue
        text = read_text(target)
        new_text, found, changed = replace_section_block(
            text, heading, block)
        if not found:
            print("render_structure_projection: %s heading %r not found "
                  "in %r" % (unit_id, heading, path))
            stale += 1
            continue
        if not changed:
            print("render_structure_projection: %s is current (%s)"
                  % (unit_id, path))
            continue
        if args.apply:
            pending.append((target, new_text, unit_id, path, heading))
        else:
            stale += 1
            print("render_structure_projection: %s is stale (%s#%s)"
                  % (unit_id, path, heading))

    currency = profile_admission.currency_errors(admission)
    currency.extend(input_currency_errors(root, input_snapshots))
    if currency:
        for error in currency:
            print("render_structure_projection: %s" % error)
        return 1
    for target, new_text, unit_id, path, heading in pending:
        kblib.atomic_write_text(target, new_text)
        written += 1
        print("render_structure_projection: wrote %s (%s#%s)"
              % (unit_id, path, heading))
    currency = profile_admission.currency_errors(admission)
    currency.extend(input_currency_errors(root, input_snapshots))
    if currency:
        for error in currency:
            print("render_structure_projection: %s" % error)
        return 1

    print("render_structure_projection: stale=%d written=%d on_demand=%d"
          % (stale, written, reported))
    if args.check and stale:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
