#!/usr/bin/env python3
"""Derived structure projection renderer — the registered generator for
Structure Registry roles declared `mode: derived`.

Rule owners:
- "kernel/K01 Scope and Architecture/05 Structural Unit Interface.md"
  (derived roles: generated by a deterministic tool, regenerated or
  invalidated when inputs change, never a canonical owner);
- "kernel/K01 Scope and Architecture/06 Support Layer Structural
  Interfaces.md" (support-layer coverage projections and derived indexes).

For every unit or support layer in the selected profile's Structure Registry
whose `coverage` role is `derived` and names this tool as `generator`, the
projection is computed from the Capability Matrix (rows whose canonical
paths sit under the unit root) plus Coverage Ledger dispositions. A role
with a rendering target (`path` + `heading`) owns exactly the block between
the `<!-- structure-projection:begin -->` / `<!-- structure-projection:end -->`
markers inside that section: `--apply` inserts or replaces only that block
(first position in the section on first insertion) and preserves every other
line, so curated reader prose in the same section is conserved. A role with
no rendering target renders to stdout only.

The block is a pure projection: it copies no Queue lifecycle, holds, batch
order, or receipts, and it never writes back into planning artifacts or page
classification.

Modes: default = report what would render; --check = exit 2 when any owned
block is stale or missing; --apply = write the owned blocks atomically.

Exit codes: 0 = current / applied, 1 = input error, 2 = --check stale.

Usage: python3 render_structure_projection.py <vault_root>
       [--profile PROFILE_DIR] [--check | --apply]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kblib

TOOL = "render_structure_projection"
TOOL_VERSION = "1.0.0"

ACTIVE_STATE_PATH = "kernel/K00 Standards Control/03 Standards Governance.md"
STRUCTURE_SLOT = "Structure Registry"
COVERAGE_LEDGER_PATH = ".cambium/state/coverage_ledger.yaml"
BEGIN = "<!-- structure-projection:begin -->"
END = "<!-- structure-projection:end -->"


def read_text(path):
    with open(path, encoding="utf-8", errors="replace") as handle:
        return handle.read()


def resolve_profile_dir(root, override, errors):
    if override:
        profile_dir = override if os.path.isabs(override) \
            else os.path.join(root, override)
        if not os.path.isdir(profile_dir):
            errors.append("--profile does not name an existing directory")
            return None
        return profile_dir
    try:
        state_text = read_text(os.path.join(root, ACTIVE_STATE_PATH))
    except OSError as exc:
        errors.append("cannot read the active Standards state: %s" % exc)
        return None
    state, parse_errors = kblib.active_standards_state(state_text)
    errors.extend(parse_errors)
    manifest = state.get("selected_profile_manifest") or ""
    if "{{" in manifest or not manifest.strip():
        errors.append("no instantiated selected_profile_manifest")
        return None
    manifest_path = os.path.join(root, manifest)
    if not os.path.isfile(manifest_path):
        errors.append("selected profile manifest does not exist")
        return None
    return os.path.dirname(manifest_path)


def registry_document(root, profile_dir, errors):
    try:
        manifest_text = read_text(os.path.join(profile_dir, "profile.md"))
    except OSError as exc:
        errors.append("cannot read the profile manifest: %s" % exc)
        return None
    bindings = kblib.profile_slot_bindings(manifest_text)
    binding = bindings.get(STRUCTURE_SLOT)
    if binding is None:
        errors.append("the manifest does not bind the Structure Registry")
        return None
    kind, detail = kblib.resolve_profile_binding(binding, root, profile_dir)
    if kind != "path":
        errors.append("Structure Registry binding does not resolve")
        return None
    try:
        return kblib.parse_yaml_subset(read_text(detail))
    except kblib.YamlSubsetError as exc:
        errors.append("cannot parse the registry: %s" % exc)
        return None


def load_matrix(root):
    for candidate in ("Corpus Planning/capability_matrix.yaml",):
        path = os.path.join(root, candidate)
        if os.path.isfile(path):
            try:
                data = kblib.parse_yaml_subset(read_text(path))
            except kblib.YamlSubsetError:
                return []
            return data.get("capabilities") or [] \
                if isinstance(data, dict) else []
    return []


def load_dispositions(root):
    path = os.path.join(root, COVERAGE_LEDGER_PATH)
    if not os.path.isfile(path):
        return {}
    try:
        data = kblib.parse_yaml_subset(read_text(path))
    except kblib.YamlSubsetError:
        return {}
    out = {}
    for page in (data or {}).get("pages") or []:
        if isinstance(page, dict) and page.get("path"):
            out[str(page["path"])] = str(
                page.get("coverage_disposition") or "")
    return out


def under_root(path, unit_root):
    return path == unit_root or path.startswith(unit_root + "/")


def render_block(unit_id, unit_root, matrix, dispositions):
    """Deterministic projection lines for one unit or layer."""
    rows = []
    for cap in matrix:
        if not isinstance(cap, dict):
            continue
        owners = [str(p) for p in cap.get("canonical_markdown_paths") or []]
        mine = [p for p in owners if under_root(p, unit_root)]
        if not mine:
            continue
        gaps = ", ".join(str(g) for g in cap.get("gap_ids") or []) or "none"
        rows.append("| `%s` | %s | %s | %s | %s | %s |" % (
            cap.get("capability_id"), cap.get("capability"),
            cap.get("current_level"), cap.get("target_level"),
            "; ".join("[[%s\\|%s]]" % (p[:-3] if p.endswith(".md") else p,
                                       os.path.basename(p)[:-3]
                                       if p.endswith(".md")
                                       else os.path.basename(p))
                      for p in mine),
            gaps))
    page_total = sum(1 for p in dispositions if under_root(p, unit_root))
    required = sum(1 for p, d in dispositions.items()
                   if under_root(p, unit_root) and d == "required")
    lines = [BEGIN,
             "Derived projection for `%s` — generated by "
             "`Tools/render_structure_projection.py` from the Capability "
             "Matrix and Coverage Ledger; regenerate instead of editing. "
             "The canonical owners remain `Corpus Planning/` and "
             "`.cambium/state/coverage_ledger.yaml`." % unit_id]
    if rows:
        lines += ["",
                  "| Capability | Name | Current | Target | Canonical "
                  "owners here | Gaps |",
                  "|---|---|---|---|---|---|"] + rows
    else:
        lines += ["", "No Capability Matrix row names a canonical owner "
                      "under this root."]
    if page_total:
        lines += ["", "Coverage Ledger records %d page(s) under this root, "
                      "%d of them `required`." % (page_total, required)]
    lines.append(END)
    return lines


def replace_section_block(text, heading, block_lines):
    """Return (new_text, found_heading, changed)."""
    lines = text.splitlines()
    out = []
    i = 0
    found = False
    changed = False
    n = len(lines)
    while i < n:
        line = lines[i]
        out.append(line)
        i += 1
        stripped = line.strip()
        if not stripped.startswith("#"):
            continue
        level = len(stripped) - len(stripped.lstrip("#"))
        title = stripped.lstrip("#").strip()
        if title != heading.strip():
            continue
        found = True
        # collect the section body up to the next heading of <= level
        body = []
        while i < n:
            peek = lines[i].strip()
            if peek.startswith("#"):
                peek_level = len(peek) - len(peek.lstrip("#"))
                if peek_level <= level:
                    break
            body.append(lines[i])
            i += 1
        # replace or insert the marker block
        if BEGIN in [b.strip() for b in body]:
            new_body = []
            in_block = False
            replaced = False
            for b in body:
                if b.strip() == BEGIN:
                    in_block = True
                    if not replaced:
                        new_body.extend(block_lines)
                        replaced = True
                    continue
                if b.strip() == END:
                    in_block = False
                    continue
                if not in_block:
                    new_body.append(b)
        else:
            new_body = ["", *block_lines, *body]
        if new_body != body:
            changed = True
        out.extend(new_body)
    return "\n".join(out) + ("\n" if text.endswith("\n") else ""), \
        found, changed


def iter_derived_targets(registry):
    for kind_name in ("units", "support_layers"):
        for item in registry.get(kind_name) or []:
            if not isinstance(item, dict):
                continue
            if kind_name == "units":
                roles = item.get("roles")
                role = roles.get("coverage") \
                    if isinstance(roles, dict) else None
            else:
                role = item.get("coverage")
            if not isinstance(role, dict) or role.get("mode") != "derived":
                continue
            generator = str(role.get("generator") or "")
            if not generator.endswith("render_structure_projection.py"):
                continue
            yield (item.get("id") or item.get("layer_id"),
                   item.get("root"), role.get("path"), role.get("heading"))


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Render derived Structure Registry coverage "
                    "projections (K01/05 derived roles).")
    parser.add_argument("vault_root")
    parser.add_argument("--profile")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    root = os.path.abspath(args.vault_root)

    errors = []
    profile_dir = resolve_profile_dir(root, args.profile, errors)
    registry = registry_document(root, profile_dir, errors) \
        if profile_dir else None
    if registry is None:
        for error in errors:
            print("render_structure_projection: %s" % error)
        return 1

    matrix = load_matrix(root)
    dispositions = load_dispositions(root)
    stale = 0
    written = 0
    reported = 0
    for unit_id, unit_root, path, heading in iter_derived_targets(registry):
        block = render_block(unit_id, unit_root, matrix, dispositions)
        if not path or not heading:
            reported += 1
            print("render_structure_projection: %s renders on demand "
                  "(no page target); %d projection line(s)"
                  % (unit_id, len(block)))
            continue
        target = os.path.join(root, path)
        if not os.path.isfile(target):
            print("render_structure_projection: %s target %r does not exist"
                  % (unit_id, path))
            stale += 1
            continue
        text = read_text(target)
        new_text, found, changed = replace_section_block(
            text, heading, block)
        if not found:
            print("render_structure_projection: %s heading %r not found "
                  "in %r" % (unit_id, heading, path))
            stale += 1
            continue
        if not changed:
            print("render_structure_projection: %s is current (%s)"
                  % (unit_id, path))
            continue
        if args.apply:
            kblib.atomic_write_text(target, new_text)
            written += 1
            print("render_structure_projection: wrote %s (%s#%s)"
                  % (unit_id, path, heading))
        else:
            stale += 1
            print("render_structure_projection: %s is stale (%s#%s)"
                  % (unit_id, path, heading))

    print("render_structure_projection: stale=%d written=%d on_demand=%d"
          % (stale, written, reported))
    if args.check and stale:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
